[package]
name = "bench"
version = "0.1.1"
edition = "2021"

[profile.release]
strip = true
debug-assertions = false

[dependencies]
structopt = "0.3.26"
tokio = { version="1.43.0", features = ["net", "rt", "rt-multi-thread", "io-util", "macros", "time"] }
